/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example;

import org.xtext.example.EntityStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EntityStandaloneSetup extends EntityStandaloneSetupGenerated {
  public static void doSetup() {
    new EntityStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
