/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.ide;

import org.xtext.example.ide.AbstractEntityIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EntityIdeModule extends AbstractEntityIdeModule {
}
