/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EntityStandaloneSetup extends EntityStandaloneSetupGenerated {

	def static void doSetup() {
		new EntityStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
